[package]
name = "ue_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_endian = "0.2.1"
widestring = "1.0.2"
elain = "0.3.0"
bitfield-struct = "0.5.6"