// Base Game
pub const OFFSET_FUNC_GETNAMES: isize = 0x10E94B0;
pub const OFFSET_STRUCT_GOBJECTS: isize = 0x753EC50;
pub const OFFSET_STRUCT_UWORLD_PROXY: isize = 0x7678520;
pub const OFFSET_FUNC_GET_DISPLAY_NAME: isize = 0x10E9440;
pub const OFFSET_FUNC_FNAME_TO_STRING: isize = 0x10EE300;
pub const OFFSET_FUNC_FNAME_STR_CONSTRUCTOR: isize = 0x10E6C00;

// UConsole
pub const OFFSET_VF_UCONSOLE_UOBJECT: isize = 0xBF21450;

// APawn
pub const OFFSET_VF_APAWN_INAVAGENT: isize = 0x5a3f380;

// ACharacter
pub const OFFSET_VF_ACHARACTER_INAVAGENT: isize = 0x5955a38;

// AController
pub const OFFSET_VF_ACONTROLLER_INAVAGENT: isize = 0x599c138;

// Main Menu
pub const OFFSET_FUNC_MAIN_MENU_CONNECT_TO_SERVER: isize = 0xDB80F0;

// Asset Registery
pub const OFFSET_FUNC_ASSET_REGISTRY_ADD_ASSET_DATA: isize = 0x1598CE0;

// Asset Manager
pub const OFFSET_FUNC_ASSET_MANAGER_IS_NON_PAK_FILENAME_ALLOWED: isize = 0x1FFD9A0;
pub const OFFSET_FUNC_ASSET_MANAGER_SCAN_PATH_FOR_PRIMARY_ASSETS: isize = 0x213F600;

// Object Library
pub const OFFSET_FUNC_OBJECT_LIBRARY_LOAD_ASSETS_AT_PATH: isize = 0x2479280;

// FPakFile
pub const OFFSET_FUNC_FPAKFILE_FIND: isize = 0x1ff9800;